# Volve Oil Production Data Science Project

## Notebook 00: Dataset Evidence and Structural Audit

This notebook verifies and audits the raw Volve production dataset before exploratory analysis or modelling.

The purpose is to establish the dataset structure, observation unit, well roles, missing-value patterns, operational states, monthly consistency, and data-quality findings without modifying the original source workbook.

## 1. Raw Dataset Verification

The original Kaggle workbook is retained unchanged in the raw-data directory. This section verifies that the project can locate the source file before any analysis is performed.

In [1]:
from pathlib import Path

PROJECT_ROOT = Path(r"F:\DataScience_Projects\Volve_Oil_Production")

RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"
DATASET_PATH = RAW_DATA_DIR / "Volve production data.xlsx"

print("Project root:", PROJECT_ROOT)
print("Raw data folder:", RAW_DATA_DIR)
print("Dataset path:", DATASET_PATH)
print("Dataset exists:", DATASET_PATH.exists())

Project root: F:\DataScience_Projects\Volve_Oil_Production
Raw data folder: F:\DataScience_Projects\Volve_Oil_Production\data\raw
Dataset path: F:\DataScience_Projects\Volve_Oil_Production\data\raw\Volve production data.xlsx
Dataset exists: True

## 2. Workbook and Schema Inspection

The workbook structure, sheet names, dataset dimensions, column names, data types, and example records are inspected before cleaning or transformation.

In [2]:
import pandas as pd

excel_file = pd.ExcelFile(DATASET_PATH)

print("Workbook sheets:")
for sheet in excel_file.sheet_names:
    print("-", sheet)

Workbook sheets:
- Daily Production Data
- Monthly Production Data

## 3. Daily Dataset Structure and Observation Unit

This section examines date coverage, wellbore counts, field and facility information, and record uniqueness.

The combination of production date and wellbore is tested to determine whether each row represents a unique daily observation for one wellbore.

In [3]:
daily_df = pd.read_excel(
    DATASET_PATH,
    sheet_name="Daily Production Data"
)

monthly_df = pd.read_excel(
    DATASET_PATH,
    sheet_name="Monthly Production Data"
)

print("Daily dataset shape:", daily_df.shape)
print("Monthly dataset shape:", monthly_df.shape)

Daily dataset shape: (15634, 24)
Monthly dataset shape: (527, 10)

In [4]:
print("DAILY PRODUCTION DATA")
print("-" * 60)

for number, column in enumerate(daily_df.columns, start=1):
    print(
        f"{number:02d}. {column:<30} "
        f"{daily_df[column].dtype}"
    )

print("\nMONTHLY PRODUCTION DATA")
print("-" * 60)

for number, column in enumerate(monthly_df.columns, start=1):
    print(
        f"{number:02d}. {column:<30} "
        f"{monthly_df[column].dtype}"
    )

DAILY PRODUCTION DATA
------------------------------------------------------------
01. DATEPRD                        datetime64[us]
02. WELL_BORE_CODE                 str
03. NPD_WELL_BORE_CODE             int64
04. NPD_WELL_BORE_NAME             str
05. NPD_FIELD_CODE                 int64
06. NPD_FIELD_NAME                 str
07. NPD_FACILITY_CODE              int64
08. NPD_FACILITY_NAME              str
09. ON_STREAM_HRS                  float64
10. AVG_DOWNHOLE_PRESSURE          float64
11. AVG_DOWNHOLE_TEMPERATURE       float64
12. AVG_DP_TUBING                  float64
13. AVG_ANNULUS_PRESS              float64
14. AVG_CHOKE_SIZE_P               float64
15. AVG_CHOKE_UOM                  str
16. AVG_WHP_P                      float64
17. AVG_WHT_P                      float64
18. DP_CHOKE_SIZE                  float64
19. BORE_OIL_VOL                   float64
20. BORE_GAS_VOL                   float64
21. BORE_WAT_VOL                   float64
22. BORE_WI_VOL                    float64
23. FLOW_KIND                      str
24. WELL_TYPE                      str

MONTHLY PRODUCTION DATA
------------------------------------------------------------
01. Wellbore name                  str
02. NPDCode                        float64
03. Year                           float64
04. Month                          float64
05. On Stream                      object
06. Oil                            object
07. Gas                            object
08. Water                          object
09. GI                             str
10. WI                             object

In [5]:
print("First 5 daily records:")
display(daily_df.head())

print("\nFirst 5 monthly records:")
display(monthly_df.head())

First 5 daily records:

,DATEPRD,WELL_BORE_CODE,NPD_WELL_BORE_CODE,NPD_WELL_BORE_NAME,NPD_FIELD_CODE,NPD_FIELD_NAME,NPD_FACILITY_CODE,NPD_FACILITY_NAME,ON_STREAM_HRS,AVG_DOWNHOLE_PRESSURE,...,AVG_CHOKE_UOM,AVG_WHP_P,AVG_WHT_P,DP_CHOKE_SIZE,BORE_OIL_VOL,BORE_GAS_VOL,BORE_WAT_VOL,BORE_WI_VOL,FLOW_KIND,WELL_TYPE
0,2014-04-07,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,0.00000,...,%,0.00000,0.00000,0.00000,0.0,0.0,0.0,NaN,production,WI
1,2014-04-08,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,NaN,...,%,0.00000,0.00000,0.00000,0.0,0.0,0.0,NaN,production,OP
2,2014-04-09,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,NaN,...,%,0.00000,0.00000,0.00000,0.0,0.0,0.0,NaN,production,OP
3,2014-04-10,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,NaN,...,%,0.00000,0.00000,0.00000,0.0,0.0,0.0,NaN,production,OP
4,2014-04-11,NO 15/9-F-1 C,7405,15/9-F-1 C,3420717,VOLVE,369304,MÆRSK INSPIRER,0.0,310.37614,...,%,33.09788,10.47992,33.07195,0.0,0.0,0.0,NaN,production,OP

First 5 monthly records:

,Wellbore name,NPDCode,Year,Month,On Stream,Oil,Gas,Water,GI,WI
0,NaN,NaN,NaN,NaN,hrs,Sm3,Sm3,Sm3,Sm3,Sm3
1,15/9-F-1 C,7405.0,2014.0,4.0,227.5,11142.47,1597936.65,0,NaN,NaN
2,15/9-F-1 C,7405.0,2014.0,5.0,733.83334,24901.95,3496229.65,783.48,NaN,NaN
3,15/9-F-1 C,7405.0,2014.0,6.0,705.91666,19617.76,2886661.69,2068.48,NaN,NaN
4,15/9-F-1 C,7405.0,2014.0,7.0,742.41666,15085.68,2249365.75,6243.98,NaN,NaN

In [6]:
print("DAILY DATASET STRUCTURE")
print("-" * 60)

print("Earliest date:", daily_df["DATEPRD"].min())
print("Latest date:", daily_df["DATEPRD"].max())

print(
    "Unique wellbore codes:",
    daily_df["WELL_BORE_CODE"].nunique()
)

print(
    "Unique NPD wellbore names:",
    daily_df["NPD_WELL_BORE_NAME"].nunique()
)

print(
    "Unique field names:",
    daily_df["NPD_FIELD_NAME"].nunique()
)

print(
    "Unique facility names:",
    daily_df["NPD_FACILITY_NAME"].nunique()
)

DAILY DATASET STRUCTURE
------------------------------------------------------------
Earliest date: 2007-09-01 00:00:00
Latest date: 2016-12-01 00:00:00
Unique wellbore codes: 7
Unique NPD wellbore names: 7
Unique field names: 1
Unique facility names: 1

In [7]:
duplicate_date_well = daily_df.duplicated(
    subset=["DATEPRD", "WELL_BORE_CODE"],
    keep=False
)

print(
    "Rows with duplicated DATEPRD + WELL_BORE_CODE:",
    duplicate_date_well.sum()
)

Rows with duplicated DATEPRD + WELL_BORE_CODE: 0

In [8]:
print("FLOW_KIND values:")
print(daily_df["FLOW_KIND"].value_counts(dropna=False))

print("\nWELL_TYPE values:")
print(daily_df["WELL_TYPE"].value_counts(dropna=False))

FLOW_KIND values:
FLOW_KIND
production    9161
injection     6473
Name: count, dtype: int64

WELL_TYPE values:
WELL_TYPE
OP    9143
WI    6491
Name: count, dtype: int64

In [9]:
print("Well type values by wellbore:")
print(
    daily_df.groupby("NPD_WELL_BORE_NAME")["WELL_TYPE"]
    .unique()
)

Well type values by wellbore:
NPD_WELL_BORE_NAME
15/9-F-1 C     [WI, OP]
15/9-F-11          [OP]
15/9-F-12          [OP]
15/9-F-14          [OP]
15/9-F-15 D        [OP]
15/9-F-4           [WI]
15/9-F-5       [WI, OP]
Name: WELL_TYPE, dtype: object

In [10]:
well_summary = (
    daily_df.groupby(
        ["NPD_WELL_BORE_NAME", "NPD_WELL_BORE_CODE"]
    )
    .agg(
        first_date=("DATEPRD", "min"),
        last_date=("DATEPRD", "max"),
        records=("DATEPRD", "size")
    )
    .reset_index()
)

display(well_summary)

  NPD_WELL_BORE_NAME  NPD_WELL_BORE_CODE first_date  last_date  records
0         15/9-F-1 C                7405 2014-04-07 2016-04-21      746
1          15/9-F-11                7078 2013-07-08 2016-09-17     1165
2          15/9-F-12                5599 2008-02-12 2016-09-17     3056
3          15/9-F-14                5351 2008-02-12 2016-09-17     3056
4        15/9-F-15 D                7289 2014-01-12 2016-09-17      978
5           15/9-F-4                5693 2007-09-01 2016-12-01     3327
6           15/9-F-5                5769 2007-09-01 2016-09-18     3306

## 4. Operational Classification and Data Quality

FLOW_KIND and WELL_TYPE are compared as a consistency check.

The comparison is treated as an audit rather than an automatic correction. Any inconsistent classifications are retained as source-data findings.

In [11]:
flow_type_table = pd.crosstab(
    daily_df["FLOW_KIND"],
    daily_df["WELL_TYPE"]
)

print("FLOW_KIND vs WELL_TYPE")
display(flow_type_table)

FLOW_KIND vs WELL_TYPE

WELL_TYPE     OP    WI
FLOW_KIND
injection      0  6473
production  9143    18

In [12]:
expected_type = {
    "production": "OP",
    "injection": "WI"
}

daily_df["EXPECTED_WELL_TYPE"] = (
    daily_df["FLOW_KIND"].map(expected_type)
)

type_mismatches = daily_df[
    daily_df["WELL_TYPE"]
    != daily_df["EXPECTED_WELL_TYPE"]
]

print(
    "FLOW_KIND / WELL_TYPE mismatches:",
    len(type_mismatches)
)

display(
    type_mismatches[
        [
            "DATEPRD",
            "NPD_WELL_BORE_NAME",
            "FLOW_KIND",
            "WELL_TYPE",
            "ON_STREAM_HRS",
            "BORE_OIL_VOL",
            "BORE_GAS_VOL",
            "BORE_WAT_VOL",
            "BORE_WI_VOL"
        ]
    ]
)

FLOW_KIND / WELL_TYPE mismatches: 18

,DATEPRD,NPD_WELL_BORE_NAME,FLOW_KIND,WELL_TYPE,ON_STREAM_HRS,BORE_OIL_VOL,BORE_GAS_VOL,BORE_WAT_VOL,BORE_WI_VOL
0,2014-04-07,15/9-F-1 C,production,WI,0.0,0.00,0.00,0.00,NaN
91,2014-07-07,15/9-F-1 C,production,WI,24.0,522.00,77846.76,154.47,NaN
15473,2016-04-11,15/9-F-5,production,WI,0.0,0.00,0.00,0.00,NaN
15496,2016-05-04,15/9-F-5,production,WI,12.0,328.70,52387.43,136.13,0.0
15579,2016-07-26,15/9-F-5,production,WI,12.0,340.52,54468.73,78.67,0.0
15580,2016-07-27,15/9-F-5,production,WI,12.0,334.18,53468.31,85.23,0.0
15581,2016-07-28,15/9-F-5,production,WI,12.0,338.69,54190.20,88.61,0.0
15582,2016-07-29,15/9-F-5,production,WI,12.0,342.77,53787.03,89.70,0.0
15583,2016-07-30,15/9-F-5,production,WI,12.0,349.25,55339.69,91.80,0.0
15584,2016-07-31,15/9-F-5,production,WI,12.0,342.39,53103.90,88.56,0.0
15585,2016-08-01,15/9-F-5,production,WI,12.0,351.38,53406.08,85.88,0.0
15621,2016-09-06,15/9-F-5,production,WI,0.0,0.00,0.00,0.00,0.0
15622,2016-09-07,15/9-F-5,production,WI,0.0,0.00,0.00,0.00,0.0
15623,2016-09-08,15/9-F-5,production,WI,0.0,0.00,0.00,0.00,0.0
15624,2016-09-09,15/9-F-5,production,WI,0.0,0.00,0.00,0.00,0.0
15625,2016-09-10,15/9-F-5,production,WI,0.0,0.00,0.00,0.00,0.0
15626,2016-09-11,15/9-F-5,production,WI,0.0,0.00,0.00,0.00,0.0
15627,2016-09-12,15/9-F-5,production,WI,0.0,0.00,0.00,0.00,0.0

## 5. Missingness and Operational Activity

Missing values are examined separately for production and injection records because many variables are operationally specific.

Missing values are therefore not automatically replaced with zero. Recorded zeros, missing measurements, inactive periods, and non-applicable variables are treated as different conditions.

In [13]:
missing_summary = pd.DataFrame({
    "missing_count": daily_df.isna().sum(),
    "missing_percentage": (
        daily_df.isna().mean() * 100
    ).round(2)
})

missing_summary = (
    missing_summary
    .sort_values(
        "missing_percentage",
        ascending=False
    )
)

display(missing_summary)

                          missing_count  missing_percentage
BORE_WI_VOL                        9928               63.50
AVG_ANNULUS_PRESS                  7744               49.53
AVG_CHOKE_SIZE_P                   6715               42.95
AVG_DOWNHOLE_TEMPERATURE           6654               42.56
AVG_DP_TUBING                      6654               42.56
AVG_DOWNHOLE_PRESSURE              6654               42.56
AVG_WHT_P                          6488               41.50
AVG_WHP_P                          6479               41.44
AVG_CHOKE_UOM                      6473               41.40
BORE_WAT_VOL                       6473               41.40
BORE_OIL_VOL                       6473               41.40
BORE_GAS_VOL                       6473               41.40
DP_CHOKE_SIZE                       294                1.88
ON_STREAM_HRS                       285                1.82
NPD_WELL_BORE_NAME                    0                0.00
WELL_BORE_CODE                        0                0.00
DATEPRD                               0                0.00
NPD_FACILITY_NAME                     0                0.00
NPD_FACILITY_CODE                     0                0.00
NPD_FIELD_NAME                        0                0.00
NPD_FIELD_CODE                        0                0.00
NPD_WELL_BORE_CODE                    0                0.00
FLOW_KIND                             0                0.00
WELL_TYPE                             0                0.00
EXPECTED_WELL_TYPE                    0                0.00

In [14]:
columns_to_check = [
    "ON_STREAM_HRS",
    "AVG_DOWNHOLE_PRESSURE",
    "AVG_DOWNHOLE_TEMPERATURE",
    "AVG_DP_TUBING",
    "AVG_ANNULUS_PRESS",
    "AVG_CHOKE_SIZE_P",
    "AVG_WHP_P",
    "AVG_WHT_P",
    "BORE_OIL_VOL",
    "BORE_GAS_VOL",
    "BORE_WAT_VOL",
    "BORE_WI_VOL"
]

for flow_kind in ["production", "injection"]:

    subset = daily_df[
        daily_df["FLOW_KIND"] == flow_kind
    ]

    summary = pd.DataFrame({
        "missing_count": subset[columns_to_check].isna().sum(),
        "missing_percentage":
            (subset[columns_to_check].isna().mean() * 100).round(2)
    })

    print(
        f"\n{flow_kind.upper()} RECORDS "
        f"(n={len(subset)})"
    )

    display(summary)

PRODUCTION RECORDS (n=9161)

                          missing_count  missing_percentage
ON_STREAM_HRS                         0                0.00
AVG_DOWNHOLE_PRESSURE               181                1.98
AVG_DOWNHOLE_TEMPERATURE            181                1.98
AVG_DP_TUBING                       181                1.98
AVG_ANNULUS_PRESS                  1271               13.87
AVG_CHOKE_SIZE_P                    242                2.64
AVG_WHP_P                             6                0.07
AVG_WHT_P                            15                0.16
BORE_OIL_VOL                          0                0.00
BORE_GAS_VOL                          0                0.00
BORE_WAT_VOL                          0                0.00
BORE_WI_VOL                        9146               99.84

INJECTION RECORDS (n=6473)

                          missing_count  missing_percentage
ON_STREAM_HRS                       285                4.40
AVG_DOWNHOLE_PRESSURE              6473              100.00
AVG_DOWNHOLE_TEMPERATURE           6473              100.00
AVG_DP_TUBING                      6473              100.00
AVG_ANNULUS_PRESS                  6473              100.00
AVG_CHOKE_SIZE_P                   6473              100.00
AVG_WHP_P                          6473              100.00
AVG_WHT_P                          6473              100.00
BORE_OIL_VOL                       6473              100.00
BORE_GAS_VOL                       6473              100.00
BORE_WAT_VOL                       6473              100.00
BORE_WI_VOL                         782               12.08

In [15]:
activity_summary = pd.DataFrame({
    "total_records":
        daily_df.groupby("FLOW_KIND").size(),

    "on_stream_missing":
        daily_df.groupby("FLOW_KIND")[
            "ON_STREAM_HRS"
        ].apply(lambda x: x.isna().sum()),

    "on_stream_zero":
        daily_df.groupby("FLOW_KIND")[
            "ON_STREAM_HRS"
        ].apply(lambda x: (x == 0).sum()),

    "on_stream_positive":
        daily_df.groupby("FLOW_KIND")[
            "ON_STREAM_HRS"
        ].apply(lambda x: (x > 0).sum())
})

display(activity_summary)

,total_records,on_stream_missing,on_stream_zero,on_stream_positive
FLOW_KIND,,,,
injection,6473,285,811,5377
production,9161,0,1141,8020

In [16]:
production_df = daily_df[
    daily_df["FLOW_KIND"] == "production"
].copy()

zero_production_summary = {
    "production_records": len(production_df),

    "zero_oil":
        (production_df["BORE_OIL_VOL"] == 0).sum(),

    "zero_gas":
        (production_df["BORE_GAS_VOL"] == 0).sum(),

    "zero_water":
        (production_df["BORE_WAT_VOL"] == 0).sum(),

    "zero_on_stream_hours":
        (production_df["ON_STREAM_HRS"] == 0).sum(),

    "positive_on_stream_hours":
        (production_df["ON_STREAM_HRS"] > 0).sum()
}

for key, value in zero_production_summary.items():
    print(f"{key}: {value}")

production_records: 9161
zero_oil: 1153
zero_gas: 1150
zero_water: 1526
zero_on_stream_hours: 1141
positive_on_stream_hours: 8020

In [17]:
active_but_zero_oil = production_df[
    (production_df["ON_STREAM_HRS"] > 0) &
    (production_df["BORE_OIL_VOL"] == 0)
]

print(
    "Active production records with zero oil:",
    len(active_but_zero_oil)
)

display(
    active_but_zero_oil[
        [
            "DATEPRD",
            "NPD_WELL_BORE_NAME",
            "ON_STREAM_HRS",
            "BORE_OIL_VOL",
            "BORE_GAS_VOL",
            "BORE_WAT_VOL"
        ]
    ].head(20)
)

Active production records with zero oil: 13

,DATEPRD,NPD_WELL_BORE_NAME,ON_STREAM_HRS,BORE_OIL_VOL,BORE_GAS_VOL,BORE_WAT_VOL
14,2014-04-21,15/9-F-1 C,11.50000,0.0,0.00,0.0
134,2014-08-19,15/9-F-1 C,0.99166,0.0,0.00,0.0
148,2014-09-02,15/9-F-1 C,3.87500,0.0,0.00,0.0
176,2014-09-30,15/9-F-1 C,8.16666,0.0,0.00,0.0
231,2014-11-24,15/9-F-1 C,15.77500,0.0,0.00,0.0
242,2014-12-05,15/9-F-1 C,14.00000,0.0,0.00,0.0
297,2015-01-29,15/9-F-1 C,13.69167,0.0,0.00,0.0
298,2015-01-30,15/9-F-1 C,14.72500,0.0,0.00,0.0
2827,2010-08-28,15/9-F-12,0.17500,0.0,535.16,0.0
3272,2011-12-13,15/9-F-12,4.30833,0.0,0.00,0.0
6580,2012-09-15,15/9-F-14,0.95833,0.0,0.00,0.0
8040,2014-01-29,15/9-F-15 D,8.14167,0.0,0.00,0.0
8041,2014-01-31,15/9-F-15 D,19.77500,0.0,0.00,0.0

In [18]:
production_with_wi = production_df[
    production_df["BORE_WI_VOL"].notna()
]

print(
    "Production records with a non-missing "
    "BORE_WI_VOL:",
    len(production_with_wi)
)

display(
    production_with_wi[
        [
            "DATEPRD",
            "NPD_WELL_BORE_NAME",
            "FLOW_KIND",
            "WELL_TYPE",
            "ON_STREAM_HRS",
            "BORE_OIL_VOL",
            "BORE_GAS_VOL",
            "BORE_WAT_VOL",
            "BORE_WI_VOL"
        ]
    ]
)

Production records with a non-missing BORE_WI_VOL: 15

,DATEPRD,NPD_WELL_BORE_NAME,FLOW_KIND,WELL_TYPE,ON_STREAM_HRS,BORE_OIL_VOL,BORE_GAS_VOL,BORE_WAT_VOL,BORE_WI_VOL
15496,2016-05-04,15/9-F-5,production,WI,12.0,328.70,52387.43,136.13,0.0
15579,2016-07-26,15/9-F-5,production,WI,12.0,340.52,54468.73,78.67,0.0
15580,2016-07-27,15/9-F-5,production,WI,12.0,334.18,53468.31,85.23,0.0
15581,2016-07-28,15/9-F-5,production,WI,12.0,338.69,54190.20,88.61,0.0
15582,2016-07-29,15/9-F-5,production,WI,12.0,342.77,53787.03,89.70,0.0
15583,2016-07-30,15/9-F-5,production,WI,12.0,349.25,55339.69,91.80,0.0
15584,2016-07-31,15/9-F-5,production,WI,12.0,342.39,53103.90,88.56,0.0
15585,2016-08-01,15/9-F-5,production,WI,12.0,351.38,53406.08,85.88,0.0
15621,2016-09-06,15/9-F-5,production,WI,0.0,0.00,0.00,0.00,0.0
15622,2016-09-07,15/9-F-5,production,WI,0.0,0.00,0.00,0.00,0.0
15623,2016-09-08,15/9-F-5,production,WI,0.0,0.00,0.00,0.00,0.0
15624,2016-09-09,15/9-F-5,production,WI,0.0,0.00,0.00,0.00,0.0
15625,2016-09-10,15/9-F-5,production,WI,0.0,0.00,0.00,0.00,0.0
15626,2016-09-11,15/9-F-5,production,WI,0.0,0.00,0.00,0.00,0.0
15627,2016-09-12,15/9-F-5,production,WI,0.0,0.00,0.00,0.00,0.0

In [19]:
injection_df = daily_df[
    daily_df["FLOW_KIND"] == "injection"
].copy()

injection_wi_status = pd.DataFrame({
    "all_injection_records": [len(injection_df)],

    "wi_volume_present": [
        injection_df["BORE_WI_VOL"].notna().sum()
    ],

    "wi_volume_missing": [
        injection_df["BORE_WI_VOL"].isna().sum()
    ],

    "active_with_wi_missing": [
        (
            (injection_df["ON_STREAM_HRS"] > 0) &
            (injection_df["BORE_WI_VOL"].isna())
        ).sum()
    ],

    "zero_hours_with_wi_missing": [
        (
            (injection_df["ON_STREAM_HRS"] == 0) &
            (injection_df["BORE_WI_VOL"].isna())
        ).sum()
    ]
})

display(injection_wi_status)

,all_injection_records,wi_volume_present,wi_volume_missing,active_with_wi_missing,zero_hours_with_wi_missing
0,6473,5691,782,0,497

In [20]:
def classify_activity(hours):
    if pd.isna(hours):
        return "unknown"
    elif hours == 0:
        return "inactive"
    else:
        return "active"


daily_df["ACTIVITY_STATE"] = (
    daily_df["ON_STREAM_HRS"]
    .apply(classify_activity)
)

activity_table = pd.crosstab(
    daily_df["FLOW_KIND"],
    daily_df["ACTIVITY_STATE"]
)

display(activity_table)

ACTIVITY_STATE  active  inactive  unknown
FLOW_KIND
injection         5377       811      285
production        8020      1141        0

## 6. Producer and Injector Well Profiles

Production and injection records are analysed separately to create well-level operational profiles.

The profiles summarise record coverage, active and inactive periods, production volumes, injection volumes, and basic well-performance characteristics.

In [21]:
producer_profile = (
    production_df
    .groupby("NPD_WELL_BORE_NAME")
    .agg(
        first_record=("DATEPRD", "min"),
        last_record=("DATEPRD", "max"),
        total_records=("DATEPRD", "size"),

        active_days=(
            "ON_STREAM_HRS",
            lambda x: (x > 0).sum()
        ),

        inactive_days=(
            "ON_STREAM_HRS",
            lambda x: (x == 0).sum()
        ),

        total_on_stream_hours=(
            "ON_STREAM_HRS",
            "sum"
        ),

        total_oil=(
            "BORE_OIL_VOL",
            "sum"
        ),

        total_gas=(
            "BORE_GAS_VOL",
            "sum"
        ),

        total_water=(
            "BORE_WAT_VOL",
            "sum"
        ),

        average_daily_oil=(
            "BORE_OIL_VOL",
            "mean"
        ),

        maximum_daily_oil=(
            "BORE_OIL_VOL",
            "max"
        )
    )
    .reset_index()
)

display(producer_profile)

,NPD_WELL_BORE_NAME,first_record,last_record,total_records,active_days,inactive_days,total_on_stream_hours,total_oil,total_gas,total_water,average_daily_oil,maximum_daily_oil
0,15/9-F-1 C,2014-04-07,2016-04-21,746,438,308,9983.53315,177709.33,2.644092e+07,207302.39,238.216260,1549.81
1,15/9-F-11,2013-07-08,2016-09-17,1165,1122,43,26006.21614,1147849.10,1.743105e+08,1090806.27,985.278197,2064.61
2,15/9-F-12,2008-02-12,2016-09-17,3056,2838,218,65204.06928,4579609.55,6.675423e+08,6833320.37,1498.563334,5901.84
3,15/9-F-14,2008-02-12,2016-09-17,3056,2724,332,62773.67519,3942233.39,5.780095e+08,7121249.74,1289.997837,5644.37
4,15/9-F-15 D,2014-01-12,2016-09-17,978,769,209,17824.83278,148518.56,2.250535e+07,52366.40,151.859468,513.12
5,15/9-F-5,2016-04-11,2016-09-17,160,129,31,2973.32502,41160.68,6.561826e+06,13533.18,257.254250,396.80

In [22]:
injector_profile = (
    injection_df
    .groupby("NPD_WELL_BORE_NAME")
    .agg(
        first_record=("DATEPRD", "min"),
        last_record=("DATEPRD", "max"),
        total_records=("DATEPRD", "size"),

        active_days=(
            "ON_STREAM_HRS",
            lambda x: (x > 0).sum()
        ),

        inactive_days=(
            "ON_STREAM_HRS",
            lambda x: (x == 0).sum()
        ),

        unknown_activity_days=(
            "ON_STREAM_HRS",
            lambda x: x.isna().sum()
        ),

        total_on_stream_hours=(
            "ON_STREAM_HRS",
            "sum"
        ),

        total_water_injected=(
            "BORE_WI_VOL",
            "sum"
        ),

        average_daily_injection=(
            "BORE_WI_VOL",
            "mean"
        ),

        maximum_daily_injection=(
            "BORE_WI_VOL",
            "max"
        )
    )
    .reset_index()
)

display(injector_profile)

,NPD_WELL_BORE_NAME,first_record,last_record,total_records,active_days,inactive_days,unknown_activity_days,total_on_stream_hours,total_water_injected,average_daily_injection,maximum_daily_injection
0,15/9-F-4,2007-09-01,2016-12-01,3327,2830,345,152,64267.16117,1.624073e+07,5431.681285,9316.0
1,15/9-F-5,2007-09-01,2016-09-18,3146,2547,466,133,57856.52806,1.408941e+07,5216.366712,10013.6

In [23]:
well_roles = (
    daily_df
    .groupby("NPD_WELL_BORE_NAME")["FLOW_KIND"]
    .unique()
)

print("Operational roles by well:")
print(well_roles)

Operational roles by well:
NPD_WELL_BORE_NAME
15/9-F-1 C                [production]
15/9-F-11                 [production]
15/9-F-12                 [production]
15/9-F-14                 [production]
15/9-F-15 D               [production]
15/9-F-4                   [injection]
15/9-F-5       [injection, production]
Name: FLOW_KIND, dtype: object

In [24]:
sensor_columns = [
    "AVG_DOWNHOLE_PRESSURE",
    "AVG_DOWNHOLE_TEMPERATURE",
    "AVG_DP_TUBING",
    "AVG_ANNULUS_PRESS",
    "AVG_CHOKE_SIZE_P",
    "AVG_WHP_P",
    "AVG_WHT_P"
]

sensor_availability = (
    production_df
    .groupby("NPD_WELL_BORE_NAME")[sensor_columns]
    .apply(
        lambda group:
        (group.notna().mean() * 100).round(2)
    )
)

display(sensor_availability)

,AVG_DOWNHOLE_PRESSURE,AVG_DOWNHOLE_TEMPERATURE,AVG_DP_TUBING,AVG_ANNULUS_PRESS,AVG_CHOKE_SIZE_P,AVG_WHP_P,AVG_WHT_P
NPD_WELL_BORE_NAME,,,,,,,
15/9-F-1 C,99.60,99.60,99.60,2.28,100.00,100.00,100.00
15/9-F-11,99.48,99.48,99.48,99.48,99.83,99.48,99.48
15/9-F-12,99.80,99.80,99.80,99.57,98.56,100.00,100.00
15/9-F-14,99.80,99.80,99.80,82.89,93.59,100.00,100.00
15/9-F-15 D,100.00,100.00,100.00,100.00,100.00,100.00,100.00
15/9-F-5,0.00,0.00,0.00,100.00,100.00,100.00,94.38

## 7. F-5 Operational Role Investigation

Well 15/9-F-5 appears in both injection and production records. Its chronology is therefore examined separately to determine when its FLOW_KIND changes and whether multiple roles occur on the same date.

In [25]:
f5_history = (
    daily_df[
        daily_df["NPD_WELL_BORE_NAME"] == "15/9-F-5"
    ]
    [
        [
            "DATEPRD",
            "FLOW_KIND",
            "WELL_TYPE",
            "ON_STREAM_HRS",
            "BORE_OIL_VOL",
            "BORE_GAS_VOL",
            "BORE_WAT_VOL",
            "BORE_WI_VOL"
        ]
    ]
    .sort_values("DATEPRD")
    .reset_index(drop=True)
)

print("F-5 total records:", len(f5_history))
print("First record:", f5_history["DATEPRD"].min())
print("Last record:", f5_history["DATEPRD"].max())

display(f5_history.head())
display(f5_history.tail())

F-5 total records: 3306
First record: 2007-09-01 00:00:00
Last record: 2016-09-18 00:00:00

,DATEPRD,FLOW_KIND,WELL_TYPE,ON_STREAM_HRS,BORE_OIL_VOL,BORE_GAS_VOL,BORE_WAT_VOL,BORE_WI_VOL
0,2007-09-01,injection,WI,NaN,NaN,NaN,NaN,NaN
1,2007-09-02,injection,WI,NaN,NaN,NaN,NaN,NaN
2,2007-09-03,injection,WI,NaN,NaN,NaN,NaN,NaN
3,2007-09-04,injection,WI,NaN,NaN,NaN,NaN,NaN
4,2007-09-05,injection,WI,NaN,NaN,NaN,NaN,NaN

,DATEPRD,FLOW_KIND,WELL_TYPE,ON_STREAM_HRS,BORE_OIL_VOL,BORE_GAS_VOL,BORE_WAT_VOL,BORE_WI_VOL
3301,2016-09-14,production,OP,0.0,0.0,0.0,0.0,NaN
3302,2016-09-15,production,OP,0.0,0.0,0.0,0.0,NaN
3303,2016-09-16,production,OP,0.0,0.0,0.0,0.0,NaN
3304,2016-09-17,production,OP,0.0,0.0,0.0,0.0,NaN
3305,2016-09-18,injection,WI,0.0,NaN,NaN,NaN,0.0

In [26]:
f5_history["ROLE_CHANGE"] = (
    f5_history["FLOW_KIND"]
    != f5_history["FLOW_KIND"].shift()
)

f5_history["ROLE_PERIOD"] = (
    f5_history["ROLE_CHANGE"].cumsum()
)

f5_role_periods = (
    f5_history
    .groupby(
        ["ROLE_PERIOD", "FLOW_KIND"],
        as_index=False
    )
    .agg(
        start_date=("DATEPRD", "min"),
        end_date=("DATEPRD", "max"),
        records=("DATEPRD", "size"),
        total_on_stream_hours=("ON_STREAM_HRS", "sum"),
        total_oil=("BORE_OIL_VOL", "sum"),
        total_water_injected=("BORE_WI_VOL", "sum")
    )
)

display(f5_role_periods)

,ROLE_PERIOD,FLOW_KIND,start_date,end_date,records,total_on_stream_hours,total_oil,total_water_injected
0,1,injection,2007-09-01,2016-04-10,3145,57856.52806,0.00,1.408941e+07
1,2,production,2016-04-11,2016-09-17,160,2973.32502,41160.68,0.000000e+00
2,3,injection,2016-09-18,2016-09-18,1,0.00000,0.00,0.000000e+00

In [27]:
f5_same_day_roles = (
    daily_df[
        daily_df["NPD_WELL_BORE_NAME"] == "15/9-F-5"
    ]
    .groupby("DATEPRD")["FLOW_KIND"]
    .nunique()
)

same_day_multiple_roles = (
    f5_same_day_roles[
        f5_same_day_roles > 1
    ]
)

print(
    "Dates where F-5 has more than one FLOW_KIND:",
    len(same_day_multiple_roles)
)

display(same_day_multiple_roles.head(20))

Dates where F-5 has more than one FLOW_KIND: 0

Series([], Name: FLOW_KIND, dtype: int64)

## 8. Monthly Dataset Cleaning and Structural Audit

The monthly sheet contains an embedded units row. A working copy is created in memory, the units row is removed, numeric data types are restored, and well-month uniqueness is checked.

The original Excel workbook remains unchanged.

In [28]:
monthly_clean = monthly_df.copy()

print("Original monthly shape:", monthly_clean.shape)

print("\nEmbedded units row:")
display(monthly_clean.iloc[[0]])

# Remove only the embedded units row
monthly_clean = (
    monthly_clean
    .iloc[1:]
    .copy()
    .reset_index(drop=True)
)

print(
    "\nShape after removing units row:",
    monthly_clean.shape
)

display(monthly_clean.head())

Original monthly shape: (527, 10)

Embedded units row:

  Wellbore name  NPDCode  Year  Month On Stream  Oil  Gas Water   GI   WI
0           NaN      NaN   NaN    NaN       hrs  Sm3  Sm3   Sm3  Sm3  Sm3

Shape after removing units row: (526, 10)

,Wellbore name,NPDCode,Year,Month,On Stream,Oil,Gas,Water,GI,WI
0,15/9-F-1 C,7405.0,2014.0,4.0,227.5,11142.47,1597936.65,0,NaN,NaN
1,15/9-F-1 C,7405.0,2014.0,5.0,733.83334,24901.95,3496229.65,783.48,NaN,NaN
2,15/9-F-1 C,7405.0,2014.0,6.0,705.91666,19617.76,2886661.69,2068.48,NaN,NaN
3,15/9-F-1 C,7405.0,2014.0,7.0,742.41666,15085.68,2249365.75,6243.98,NaN,NaN
4,15/9-F-1 C,7405.0,2014.0,8.0,432.99166,6970.43,1048190.8,4529.75,NaN,NaN

In [29]:
monthly_numeric_columns = [
    "NPDCode",
    "Year",
    "Month",
    "On Stream",
    "Oil",
    "Gas",
    "Water",
    "GI",
    "WI"
]

for column in monthly_numeric_columns:
    monthly_clean[column] = pd.to_numeric(
        monthly_clean[column],
        errors="coerce"
    )

monthly_clean["NPDCode"] = (
    monthly_clean["NPDCode"].astype("int64")
)

monthly_clean["Year"] = (
    monthly_clean["Year"].astype("int64")
)

monthly_clean["Month"] = (
    monthly_clean["Month"].astype("int64")
)

monthly_clean["MONTH_START"] = pd.to_datetime(
    {
        "year": monthly_clean["Year"],
        "month": monthly_clean["Month"],
        "day": 1
    }
)

print("MONTHLY DATA TYPES")
print("-" * 60)
print(monthly_clean.dtypes)

print("\nFirst cleaned monthly records:")
display(monthly_clean.head())

MONTHLY DATA TYPES
------------------------------------------------------------
Wellbore name               str
NPDCode                   int64
Year                      int64
Month                     int64
On Stream               float64
Oil                     float64
Gas                     float64
Water                   float64
GI                      float64
WI                      float64
MONTH_START      datetime64[us]
dtype: object

First cleaned monthly records:

,Wellbore name,NPDCode,Year,Month,On Stream,Oil,Gas,Water,GI,WI,MONTH_START
0,15/9-F-1 C,7405,2014,4,227.50000,11142.47,1597936.65,0.00,NaN,NaN,2014-04-01
1,15/9-F-1 C,7405,2014,5,733.83334,24901.95,3496229.65,783.48,NaN,NaN,2014-05-01
2,15/9-F-1 C,7405,2014,6,705.91666,19617.76,2886661.69,2068.48,NaN,NaN,2014-06-01
3,15/9-F-1 C,7405,2014,7,742.41666,15085.68,2249365.75,6243.98,NaN,NaN,2014-07-01
4,15/9-F-1 C,7405,2014,8,432.99166,6970.43,1048190.80,4529.75,NaN,NaN,2014-08-01

In [30]:
monthly_duplicate_mask = (
    monthly_clean.duplicated(
        subset=[
            "Wellbore name",
            "Year",
            "Month"
        ],
        keep=False
    )
)

monthly_missing_summary = pd.DataFrame({
    "missing_count":
        monthly_clean.isna().sum(),

    "missing_percentage":
        (
            monthly_clean.isna().mean()
            * 100
        ).round(2)
})

monthly_records_by_well = (
    monthly_clean
    .groupby("Wellbore name")
    .size()
    .rename("monthly_records")
    .reset_index()
)

print("MONTHLY DATASET STRUCTURE")
print("-" * 60)

print("Rows:", len(monthly_clean))

print(
    "Unique wellbores:",
    monthly_clean["Wellbore name"].nunique()
)

print(
    "Earliest month:",
    monthly_clean["MONTH_START"].min()
)

print(
    "Latest month:",
    monthly_clean["MONTH_START"].max()
)

print(
    "Duplicated well + year + month rows:",
    monthly_duplicate_mask.sum()
)

print(
    "GI non-missing values:",
    monthly_clean["GI"].notna().sum()
)

print(
    "WI non-missing values:",
    monthly_clean["WI"].notna().sum()
)

print("\nRecords by well:")
display(monthly_records_by_well)

print("\nMonthly missing values:")
display(monthly_missing_summary)

MONTHLY DATASET STRUCTURE
------------------------------------------------------------
Rows: 526
Unique wellbores: 7
Earliest month: 2007-09-01 00:00:00
Latest month: 2016-12-01 00:00:00
Duplicated well + year + month rows: 0
GI non-missing values: 0
WI non-missing values: 201

Records by well:

  Wellbore name  monthly_records
0    15/9-F-1 C               25
1     15/9-F-11               39
2     15/9-F-12              104
3     15/9-F-14              104
4   15/9-F-15 D               33
5      15/9-F-4              112
6      15/9-F-5              109

Monthly missing values:

               missing_count  missing_percentage
Wellbore name              0                0.00
NPDCode                    0                0.00
Year                       0                0.00
Month                      0                0.00
On Stream                 11                2.09
Oil                      215               40.87
Gas                      215               40.87
Water                    215               40.87
GI                       526              100.00
WI                       325               61.79
MONTH_START                0                0.00

## 9. Daily-to-Monthly Reconciliation

The daily dataset is independently aggregated by well, year, and month.

These calculated monthly totals are then compared with the supplied Monthly Production Data sheet to verify that the daily data has been interpreted correctly.

In [31]:
daily_for_monthly = daily_df.copy()

daily_for_monthly["Year"] = (
    daily_for_monthly["DATEPRD"].dt.year
)

daily_for_monthly["Month"] = (
    daily_for_monthly["DATEPRD"].dt.month
)


def sum_preserve_missing(series):
    return series.sum(min_count=1)


daily_monthly_agg = (
    daily_for_monthly
    .groupby(
        [
            "NPD_WELL_BORE_NAME",
            "NPD_WELL_BORE_CODE",
            "Year",
            "Month"
        ],
        as_index=False
    )
    .agg(
        daily_rows=(
            "DATEPRD",
            "size"
        ),

        flow_kinds=(
            "FLOW_KIND",
            lambda series:
                ", ".join(
                    sorted(
                        series.dropna().unique()
                    )
                )
        ),

        daily_on_stream=(
            "ON_STREAM_HRS",
            sum_preserve_missing
        ),

        daily_oil=(
            "BORE_OIL_VOL",
            sum_preserve_missing
        ),

        daily_gas=(
            "BORE_GAS_VOL",
            sum_preserve_missing
        ),

        daily_water=(
            "BORE_WAT_VOL",
            sum_preserve_missing
        ),

        daily_wi=(
            "BORE_WI_VOL",
            sum_preserve_missing
        )
    )
)

print(
    "Daily data aggregated to monthly rows:",
    len(daily_monthly_agg)
)

display(daily_monthly_agg.head(10))
mixed_role_months = daily_monthly_agg[
    daily_monthly_agg[
        "flow_kinds"
    ].str.contains(",")
]

print(
    "\nMonths containing more than one FLOW_KIND:",
    len(mixed_role_months)
)

display(mixed_role_months)

Daily data aggregated to monthly rows: 526

,NPD_WELL_BORE_NAME,NPD_WELL_BORE_CODE,Year,Month,daily_rows,flow_kinds,daily_on_stream,daily_oil,daily_gas,daily_water,daily_wi
0,15/9-F-1 C,7405,2014,4,24,production,227.50000,11142.47,1597936.65,0.00,NaN
1,15/9-F-1 C,7405,2014,5,31,production,733.83334,24901.95,3496229.65,783.48,NaN
2,15/9-F-1 C,7405,2014,6,30,production,705.91666,19617.76,2886661.69,2068.48,NaN
3,15/9-F-1 C,7405,2014,7,31,production,742.41666,15085.68,2249365.75,6243.98,NaN
4,15/9-F-1 C,7405,2014,8,31,production,432.99166,6970.43,1048190.80,4529.75,NaN
5,15/9-F-1 C,7405,2014,9,30,production,630.30000,9168.43,1414099.99,8317.59,NaN
6,15/9-F-1 C,7405,2014,10,31,production,745.00000,9468.06,1462063.99,10364.87,NaN
7,15/9-F-1 C,7405,2014,11,30,production,579.77500,6710.33,1044188.30,7234.24,NaN
8,15/9-F-1 C,7405,2014,12,31,production,27.50000,120.29,25857.08,183.44,NaN
9,15/9-F-1 C,7405,2015,1,31,production,479.91667,10875.53,1604934.60,6850.80,NaN

Months containing more than one FLOW_KIND: 2

,NPD_WELL_BORE_NAME,NPD_WELL_BORE_CODE,Year,Month,daily_rows,flow_kinds,daily_on_stream,daily_oil,daily_gas,daily_water,daily_wi
520,15/9-F-5,5769,2016,4,30,"injection, production",345.41668,3400.61,538638.56,2380.78,20226.95879
525,15/9-F-5,5769,2016,9,18,"injection, production",0.00000,0.00,0.00,0.00,0.00000

In [32]:
monthly_for_compare = (
    monthly_clean
    .rename(
        columns={
            "Wellbore name":
                "NPD_WELL_BORE_NAME",

            "NPDCode":
                "NPD_WELL_BORE_CODE",

            "On Stream":
                "monthly_on_stream",

            "Oil":
                "monthly_oil",

            "Gas":
                "monthly_gas",

            "Water":
                "monthly_water",

            "WI":
                "monthly_wi"
        }
    )
    .copy()
)

comparison = daily_monthly_agg.merge(
    monthly_for_compare[
        [
            "NPD_WELL_BORE_NAME",
            "NPD_WELL_BORE_CODE",
            "Year",
            "Month",
            "monthly_on_stream",
            "monthly_oil",
            "monthly_gas",
            "monthly_water",
            "monthly_wi"
        ]
    ],

    on=[
        "NPD_WELL_BORE_NAME",
        "NPD_WELL_BORE_CODE",
        "Year",
        "Month"
    ],

    how="outer",
    validate="one_to_one",
    indicator=True
)

print("DAILY ↔ MONTHLY ROW ALIGNMENT")
print("-" * 60)

print(comparison["_merge"].value_counts())

display(comparison.head())

DAILY ↔ MONTHLY ROW ALIGNMENT
------------------------------------------------------------
_merge
both          526
left_only       0
right_only      0
Name: count, dtype: int64

,NPD_WELL_BORE_NAME,NPD_WELL_BORE_CODE,Year,Month,daily_rows,flow_kinds,daily_on_stream,daily_oil,daily_gas,daily_water,daily_wi,monthly_on_stream,monthly_oil,monthly_gas,monthly_water,monthly_wi,_merge
0,15/9-F-1 C,7405,2014,4,24,production,227.50000,11142.47,1597936.65,0.00,NaN,227.50000,11142.47,1597936.65,0.00,NaN,both
1,15/9-F-1 C,7405,2014,5,31,production,733.83334,24901.95,3496229.65,783.48,NaN,733.83334,24901.95,3496229.65,783.48,NaN,both
2,15/9-F-1 C,7405,2014,6,30,production,705.91666,19617.76,2886661.69,2068.48,NaN,705.91666,19617.76,2886661.69,2068.48,NaN,both
3,15/9-F-1 C,7405,2014,7,31,production,742.41666,15085.68,2249365.75,6243.98,NaN,742.41666,15085.68,2249365.75,6243.98,NaN,both
4,15/9-F-1 C,7405,2014,8,31,production,432.99166,6970.43,1048190.80,4529.75,NaN,432.99166,6970.43,1048190.80,4529.75,NaN,both

### 9.1 Numerical Reconciliation

For jointly observed values, daily-derived monthly totals are compared numerically with the supplied monthly totals using a small floating-point tolerance.

Missing-versus-zero representation differences are reported separately rather than automatically changed.

In [33]:
import numpy as np


metric_pairs = {
    "on_stream": (
        "daily_on_stream",
        "monthly_on_stream"
    ),

    "oil": (
        "daily_oil",
        "monthly_oil"
    ),

    "gas": (
        "daily_gas",
        "monthly_gas"
    ),

    "water": (
        "daily_water",
        "monthly_water"
    ),

    "wi": (
        "daily_wi",
        "monthly_wi"
    )
}


reconciliation_rows = []
representation_frames = []


for metric, columns in metric_pairs.items():

    daily_column, monthly_column = columns

    both_present = (
        comparison[daily_column].notna()
        &
        comparison[monthly_column].notna()
    )

    one_side_missing = (
        comparison[daily_column].isna()
        ^
        comparison[monthly_column].isna()
    )

    daily_values = comparison.loc[
        both_present,
        daily_column
    ]

    monthly_values = comparison.loc[
        both_present,
        monthly_column
    ]

    absolute_difference = (
        daily_values - monthly_values
    ).abs()

    within_tolerance = np.isclose(
        daily_values,
        monthly_values,
        rtol=1e-9,
        atol=1e-6
    )

    reconciliation_rows.append({
        "metric": metric,

        "both_present":
            int(both_present.sum()),

        "within_tolerance":
            int(within_tolerance.sum()),

        "one_side_missing":
            int(one_side_missing.sum()),

        "maximum_absolute_difference":
            (
                absolute_difference.max()
                if len(absolute_difference) > 0
                else np.nan
            )
    })

    if one_side_missing.any():

        representation_difference = (
            comparison.loc[
                one_side_missing,
                [
                    "NPD_WELL_BORE_NAME",
                    "Year",
                    "Month",
                    daily_column,
                    monthly_column
                ]
            ]
            .copy()
        )

        representation_difference.insert(
            0,
            "metric",
            metric
        )

        representation_frames.append(
            representation_difference
        )


reconciliation_summary = pd.DataFrame(
    reconciliation_rows
)

print("NUMERICAL RECONCILIATION")
print("-" * 60)

display(reconciliation_summary)


if representation_frames:

    representation_differences = pd.concat(
        representation_frames,
        ignore_index=True
    )

    print(
        "\nMissing / zero representation differences:"
    )

    display(representation_differences)

else:

    representation_differences = (
        pd.DataFrame()
    )

    print(
        "\nNo one-sided missing-value "
        "differences found."
    )

NUMERICAL RECONCILIATION
------------------------------------------------------------

,metric,both_present,within_tolerance,one_side_missing,maximum_absolute_difference
0,on_stream,515,515,0,1.136868e-13
1,oil,311,311,0,2.910383e-11
2,gas,311,311,0,7.450581e-09
3,water,311,311,0,5.820766e-11
4,wi,200,200,1,4.656613e-10

Missing / zero representation differences:

  metric NPD_WELL_BORE_NAME  Year  Month  daily_wi  monthly_wi
0     wi           15/9-F-4  2008      3       NaN         0.0

## 10. Refined Active-Day Well Profiles

Recorded-day averages include shutdown days, while active-day averages use only records where ON_STREAM_HRS is greater than zero.

Both measures are retained because they describe different aspects of well performance.

In [34]:
active_production_df = production_df[
    production_df["ON_STREAM_HRS"] > 0
].copy()

active_injection_df = injection_df[
    injection_df["ON_STREAM_HRS"] > 0
].copy()


producer_profile_refined = (
    production_df
    .groupby("NPD_WELL_BORE_NAME")
    .agg(
        total_records=(
            "DATEPRD",
            "size"
        ),

        active_days=(
            "ON_STREAM_HRS",
            lambda series:
                (series > 0).sum()
        ),

        inactive_days=(
            "ON_STREAM_HRS",
            lambda series:
                (series == 0).sum()
        ),

        total_oil=(
            "BORE_OIL_VOL",
            "sum"
        ),

        average_recorded_day_oil=(
            "BORE_OIL_VOL",
            "mean"
        ),

        maximum_daily_oil=(
            "BORE_OIL_VOL",
            "max"
        )
    )
    .reset_index()
)


producer_active_average = (
    active_production_df
    .groupby("NPD_WELL_BORE_NAME")[
        "BORE_OIL_VOL"
    ]
    .mean()
    .rename("average_active_day_oil")
    .reset_index()
)


producer_profile_refined = (
    producer_profile_refined
    .merge(
        producer_active_average,
        on="NPD_WELL_BORE_NAME",
        how="left"
    )
)


injector_profile_refined = (
    injection_df
    .groupby("NPD_WELL_BORE_NAME")
    .agg(
        total_records=(
            "DATEPRD",
            "size"
        ),

        active_days=(
            "ON_STREAM_HRS",
            lambda series:
                (series > 0).sum()
        ),

        inactive_days=(
            "ON_STREAM_HRS",
            lambda series:
                (series == 0).sum()
        ),

        unknown_activity_days=(
            "ON_STREAM_HRS",
            lambda series:
                series.isna().sum()
        ),

        total_water_injected=(
            "BORE_WI_VOL",
            "sum"
        ),

        average_available_day_injection=(
            "BORE_WI_VOL",
            "mean"
        ),

        maximum_daily_injection=(
            "BORE_WI_VOL",
            "max"
        )
    )
    .reset_index()
)


injector_active_average = (
    active_injection_df
    .groupby("NPD_WELL_BORE_NAME")[
        "BORE_WI_VOL"
    ]
    .mean()
    .rename(
        "average_active_day_injection"
    )
    .reset_index()
)


injector_profile_refined = (
    injector_profile_refined
    .merge(
        injector_active_average,
        on="NPD_WELL_BORE_NAME",
        how="left"
    )
)


print("REFINED PRODUCER PROFILE")
display(producer_profile_refined)

print("\nREFINED INJECTOR PROFILE")
display(injector_profile_refined)

REFINED PRODUCER PROFILE

,NPD_WELL_BORE_NAME,total_records,active_days,inactive_days,total_oil,average_recorded_day_oil,maximum_daily_oil,average_active_day_oil
0,15/9-F-1 C,746,438,308,177709.33,238.216260,1549.81,405.729064
1,15/9-F-11,1165,1122,43,1147849.10,985.278197,2064.61,1022.123467
2,15/9-F-12,3056,2838,218,4579609.55,1498.563334,5901.84,1613.674965
3,15/9-F-14,3056,2724,332,3942233.39,1289.997837,5644.37,1447.222243
4,15/9-F-15 D,978,769,209,148518.56,151.859468,513.12,193.132068
5,15/9-F-5,160,129,31,41160.68,257.254250,396.80,319.075039

REFINED INJECTOR PROFILE

,NPD_WELL_BORE_NAME,total_records,active_days,inactive_days,unknown_activity_days,total_water_injected,average_available_day_injection,maximum_daily_injection,average_active_day_injection
0,15/9-F-4,3327,2830,345,152,1.624073e+07,5431.681285,9316.0,5736.558697
1,15/9-F-5,3146,2547,466,133,1.408941e+07,5216.366712,10013.6,5531.453242

## 11. Sensor Availability During Active Production

Sensor completeness is recalculated using only active production records.

This provides a more relevant view of which operational measurements may realistically be available for later modelling.

In [35]:
sensor_availability_active = (
    active_production_df
    .groupby(
        "NPD_WELL_BORE_NAME"
    )[sensor_columns]
    .apply(
        lambda group:
            (
                group.notna().mean()
                * 100
            ).round(2)
    )
)

print(
    "SENSOR AVAILABILITY "
    "DURING ACTIVE PRODUCTION (%)"
)

display(sensor_availability_active)

SENSOR AVAILABILITY DURING ACTIVE PRODUCTION (%)

,AVG_DOWNHOLE_PRESSURE,AVG_DOWNHOLE_TEMPERATURE,AVG_DP_TUBING,AVG_ANNULUS_PRESS,AVG_CHOKE_SIZE_P,AVG_WHP_P,AVG_WHT_P
NPD_WELL_BORE_NAME,,,,,,,
15/9-F-1 C,100.00,100.00,100.00,0.46,100.0,100.00,100.00
15/9-F-11,99.73,99.73,99.73,99.73,100.0,99.73,99.73
15/9-F-12,99.79,99.79,99.79,99.54,100.0,100.00,100.00
15/9-F-14,99.78,99.78,99.78,81.68,100.0,100.00,100.00
15/9-F-15 D,100.00,100.00,100.00,100.00,100.0,100.00,100.00
15/9-F-5,0.00,0.00,0.00,100.00,100.0,100.00,100.00

## 12. Final Audit Checks and Documented Findings

Automated checks summarise whether the key structural conditions of the dataset have passed.

Known irregularities remain documented separately and are not hidden or automatically corrected.

In [36]:
core_numeric_reconciliation_passed = (
    reconciliation_summary[
        "both_present"
    ]
    ==
    reconciliation_summary[
        "within_tolerance"
    ]
).all()


audit_checks = pd.DataFrame([
    {
        "check":
            "Raw workbook is accessible",

        "status":
            "PASS"
            if DATASET_PATH.exists()
            else "REVIEW"
    },

    {
        "check":
            "Daily well-date keys are unique",

        "status":
            "PASS"
            if daily_df.duplicated(
                subset=[
                    "DATEPRD",
                    "WELL_BORE_CODE"
                ]
            ).sum() == 0
            else "REVIEW"
    },

    {
        "check":
            "Monthly well-year-month keys are unique",

        "status":
            "PASS"
            if monthly_duplicate_mask.sum() == 0
            else "REVIEW"
    },

    {
        "check":
            "Daily and monthly well-month keys align",

        "status":
            "PASS"
            if comparison["_merge"]
                .eq("both").all()
            else "REVIEW"
    },

    {
        "check":"All jointly observed monthly totals reconcile",

        "status":
            "PASS"
            if core_numeric_reconciliation_passed
            else "REVIEW"
    },

    {
        "check":
            "Active production rows have oil values",

        "status":
            "PASS"
            if active_production_df[
                "BORE_OIL_VOL"
            ].isna().sum() == 0
            else "REVIEW"
    },

    {
        "check":
            "Active injection rows have WI values",

        "status":
            "PASS"
            if active_injection_df[
                "BORE_WI_VOL"
            ].isna().sum() == 0
            else "REVIEW"
    },

    {
        "check":
            "F-5 has no same-day dual FLOW_KIND",

        "status":
            "PASS"
            if len(
                same_day_multiple_roles
            ) == 0
            else "REVIEW"
    }
])


audit_findings = pd.DataFrame([
    {
        "finding":
            "FLOW_KIND / WELL_TYPE mismatches",

        "count":
            len(type_mismatches)
    },

    {
        "finding":
            "Active production rows with zero oil",

        "count":
            len(active_but_zero_oil)
    },

    {
        "finding":
            "Monthly GI non-missing records",

        "count":
            monthly_clean[
                "GI"
            ].notna().sum()
    },

    {
        "finding":
            "Daily/monthly one-sided "
            "missing-value representations",

        "count":
            len(representation_differences)
    }
])


print("FINAL AUDIT CHECKS")
print("-" * 60)

display(audit_checks)

print("\nDOCUMENTED AUDIT FINDINGS")
display(audit_findings)

FINAL AUDIT CHECKS
------------------------------------------------------------

                                           check status
0                     Raw workbook is accessible   PASS
1                Daily well-date keys are unique   PASS
2        Monthly well-year-month keys are unique   PASS
3        Daily and monthly well-month keys align   PASS
4  All jointly observed monthly totals reconcile   PASS
5         Active production rows have oil values   PASS
6           Active injection rows have WI values   PASS
7             F-5 has no same-day dual FLOW_KIND   PASS

DOCUMENTED AUDIT FINDINGS

                                             finding  count
0                   FLOW_KIND / WELL_TYPE mismatches     18
1               Active production rows with zero oil     13
2                     Monthly GI non-missing records      0
3  Daily/monthly one-sided missing-value represen...      1

## 13. Saving Audit Evidence

The cleaned monthly working dataset and audit outputs are saved to the project folders so that later notebooks can use reproducible evidence without modifying the raw workbook.

In [37]:
INTERIM_DATA_DIR = (
    PROJECT_ROOT
    / "data"
    / "interim"
)

OUTPUTS_DIR = (
    PROJECT_ROOT
    / "outputs"
)

INTERIM_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)

OUTPUTS_DIR.mkdir(
    parents=True,
    exist_ok=True
)


monthly_clean.to_csv(
    INTERIM_DATA_DIR
    / "monthly_production_clean.csv",
    index=False
)


comparison.to_csv(
    OUTPUTS_DIR
    / "00_daily_monthly_reconciliation.csv",
    index=False
)


reconciliation_summary.to_csv(
    OUTPUTS_DIR
    / "00_reconciliation_summary.csv",
    index=False
)


producer_profile_refined.to_csv(
    OUTPUTS_DIR
    / "00_producer_profile_refined.csv",
    index=False
)


injector_profile_refined.to_csv(
    OUTPUTS_DIR
    / "00_injector_profile_refined.csv",
    index=False
)


sensor_availability_active.reset_index().to_csv(
    OUTPUTS_DIR
    / "00_active_sensor_availability.csv",
    index=False
)


f5_role_periods.to_csv(
    OUTPUTS_DIR
    / "00_f5_role_periods.csv",
    index=False
)


audit_checks.to_csv(
    OUTPUTS_DIR
    / "00_audit_checks.csv",
    index=False
)


audit_findings.to_csv(
    OUTPUTS_DIR
    / "00_audit_findings.csv",
    index=False
)


print("NOTEBOOK 00 OUTPUTS SAVED")
print("-" * 60)

print(
    "Interim monthly dataset:",
    INTERIM_DATA_DIR
    / "monthly_production_clean.csv"
)

print(
    "\nAudit outputs folder:",
    OUTPUTS_DIR
)

NOTEBOOK 00 OUTPUTS SAVED
------------------------------------------------------------
Interim monthly dataset: F:\DataScience_Projects\Volve_Oil_Production\data\interim\monthly_production_clean.csv

Audit outputs folder: F:\DataScience_Projects\Volve_Oil_Production\outputs

## 14. Notebook 00 Conclusion

The raw Volve workbook was successfully verified and structurally audited.

Key findings include:

- the daily dataset contains unique well-date observations;
- production and injection records have distinct variable-availability patterns;
- operational missingness is often structural rather than random;
- well 15/9-F-5 changes operational role across its recorded history without simultaneous same-day roles;
- the daily and monthly well-month structures align completely;
- all jointly observed monthly production and injection totals reconcile within numerical tolerance;
- sensor availability differs across producer wells and must be considered during later modelling;
- identified source-data irregularities have been retained and documented rather than automatically corrected.

The dataset is therefore suitable to proceed to exploratory production and well-behaviour analysis.